#!/bin/sh

# PROVIDE: pen_proxy
# REQUIRE: SERVERS ldconfig
# BEFORE:  DAEMON named
# KEYWORD: shutdown

. /etc/rc.subr

name=pen_proxy
rcvar=pen_proxy_enable

command="/usr/local/bin/${name}"
pidfile="/var/run/linas/${name}.pid"

command_args="--config /usr/local/etc/linas/pen_proxy.conf --daemon"
start_precmd="mkdir -p /var/run/linas /var/log/linas"

load_rc_config $name
run_rc_command "$1"
